### PR TITLE
Harmony

### PR DESCRIPTION
**Pull request by iam4x**
Should fix https://github.com/AtomLinter/linter-jsxhint/issues/14 and https://github.com/AtomLinter/linter-jsxhint/issues/12

### CODE REVIEW

**Comment by iam4x** [comment]
What are your thought on this @dmnd ?

**Comment by dmnd** [comment]
Personally, I've already switched to eslint since that supports JSX natively. If this fixes problems for users of jsxhint though, I'm :+1:.

**Comment by iam4x** [comment]
Alright I will merge it and release ;)

**Comment by hd-deman** [comment]
@iam4x, @dmnd  don't forget to update notable changes in releases when you publish something new release and update release draft if you merge PRs. https://github.com/AtomLinter/linter-jsxhint/releases

**Pull request merged**
